###
GET https://eu1.cloud.thethings.network/api/v3/as/applications/harryb-water-level/packages/storage/uplink_message
Authorization: Bearer NNSXS.DEG.......
Accept: text/event-stream


###
GET https://eu1.cloud.thethings.network/api/v3/as/applications/harryb-water-level/devices/madrid-4827e2fffec71940/packages/storage/uplink_message
Authorization: Bearer NNSXS.DEG.......
Accept: text/event-stream
